{"context":"ExceptionsHandler","level":"error","message":"Service Unavailable","timestamp":"2024-11-10T16:35:09.372Z","trace":"FastifyError: Service Unavailable\n    at fastifyUnderPressure (/Users/richard/osp/bumblebee/node_modules/.pnpm/@fastify+under-pressure@9.0.1/node_modules/@fastify/under-pressure/index.js:143:30)\n    at Plugin.exec (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/lib/plugin.js:125:28)\n    at Boot._loadPlugin (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/boot.js:432:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"}
{"context":"ExceptionsHandler","level":"error","message":"Service Unavailable","timestamp":"2024-11-10T16:35:15.432Z","trace":"FastifyError: Service Unavailable\n    at fastifyUnderPressure (/Users/richard/osp/bumblebee/node_modules/.pnpm/@fastify+under-pressure@9.0.1/node_modules/@fastify/under-pressure/index.js:143:30)\n    at Plugin.exec (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/lib/plugin.js:125:28)\n    at Boot._loadPlugin (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/boot.js:432:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"}
{"context":"ExceptionsHandler","level":"error","message":"Service Unavailable","timestamp":"2024-11-10T16:35:17.508Z","trace":"FastifyError: Service Unavailable\n    at fastifyUnderPressure (/Users/richard/osp/bumblebee/node_modules/.pnpm/@fastify+under-pressure@9.0.1/node_modules/@fastify/under-pressure/index.js:143:30)\n    at Plugin.exec (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/lib/plugin.js:125:28)\n    at Boot._loadPlugin (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/boot.js:432:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"}
{"context":"ExceptionsHandler","level":"error","message":"Service Unavailable","timestamp":"2024-11-10T16:35:18.736Z","trace":"FastifyError: Service Unavailable\n    at fastifyUnderPressure (/Users/richard/osp/bumblebee/node_modules/.pnpm/@fastify+under-pressure@9.0.1/node_modules/@fastify/under-pressure/index.js:143:30)\n    at Plugin.exec (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/lib/plugin.js:125:28)\n    at Boot._loadPlugin (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/boot.js:432:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"}
{"context":"ExceptionsHandler","level":"error","message":"Service Unavailable","timestamp":"2024-11-10T16:35:19.281Z","trace":"FastifyError: Service Unavailable\n    at fastifyUnderPressure (/Users/richard/osp/bumblebee/node_modules/.pnpm/@fastify+under-pressure@9.0.1/node_modules/@fastify/under-pressure/index.js:143:30)\n    at Plugin.exec (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/lib/plugin.js:125:28)\n    at Boot._loadPlugin (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/boot.js:432:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"}
{"context":"ExceptionsHandler","level":"error","message":"Service Unavailable","timestamp":"2024-11-10T16:35:19.847Z","trace":"FastifyError: Service Unavailable\n    at fastifyUnderPressure (/Users/richard/osp/bumblebee/node_modules/.pnpm/@fastify+under-pressure@9.0.1/node_modules/@fastify/under-pressure/index.js:143:30)\n    at Plugin.exec (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/lib/plugin.js:125:28)\n    at Boot._loadPlugin (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/boot.js:432:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"}
{"context":"ExceptionHandler","level":"error","message":"","timestamp":"2024-11-10T16:47:11.237Z","trace":"AggregateError [ECONNREFUSED]: \n    at internalConnectMultiple (node:net:1121:18)\n    at afterConnectMultiple (node:net:1688:7)"}
{"context":"ExceptionHandler","level":"error","message":"","timestamp":"2024-11-10T16:47:52.394Z","trace":"AggregateError [ECONNREFUSED]: \n    at internalConnectMultiple (node:net:1121:18)\n    at afterConnectMultiple (node:net:1688:7)"}
{"context":"ExceptionsHandler","level":"error","message":"Service Unavailable","timestamp":"2024-11-10T16:48:08.715Z","trace":"FastifyError: Service Unavailable\n    at fastifyUnderPressure (/Users/richard/osp/bumblebee/node_modules/.pnpm/@fastify+under-pressure@9.0.1/node_modules/@fastify/under-pressure/index.js:143:30)\n    at Plugin.exec (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/lib/plugin.js:125:28)\n    at Boot._loadPlugin (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/boot.js:432:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"}
{"context":"ExceptionsHandler","level":"error","message":"Service Unavailable","timestamp":"2024-11-10T16:48:11.483Z","trace":"FastifyError: Service Unavailable\n    at fastifyUnderPressure (/Users/richard/osp/bumblebee/node_modules/.pnpm/@fastify+under-pressure@9.0.1/node_modules/@fastify/under-pressure/index.js:143:30)\n    at Plugin.exec (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/lib/plugin.js:125:28)\n    at Boot._loadPlugin (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/boot.js:432:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"}
{"context":"ExceptionsHandler","level":"error","message":"Service Unavailable","timestamp":"2024-11-10T16:48:49.354Z","trace":"FastifyError: Service Unavailable\n    at fastifyUnderPressure (/Users/richard/osp/bumblebee/node_modules/.pnpm/@fastify+under-pressure@9.0.1/node_modules/@fastify/under-pressure/index.js:143:30)\n    at Plugin.exec (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/lib/plugin.js:125:28)\n    at Boot._loadPlugin (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/boot.js:432:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"}
{"context":"ExceptionsHandler","level":"error","message":"Service Unavailable","timestamp":"2024-11-10T16:49:06.338Z","trace":"FastifyError: Service Unavailable\n    at fastifyUnderPressure (/Users/richard/osp/bumblebee/node_modules/.pnpm/@fastify+under-pressure@9.0.1/node_modules/@fastify/under-pressure/index.js:143:30)\n    at Plugin.exec (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/lib/plugin.js:125:28)\n    at Boot._loadPlugin (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/boot.js:432:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"}
{"context":"ExceptionsHandler","level":"error","message":"Service Unavailable","timestamp":"2024-11-10T16:49:13.128Z","trace":"FastifyError: Service Unavailable\n    at fastifyUnderPressure (/Users/richard/osp/bumblebee/node_modules/.pnpm/@fastify+under-pressure@9.0.1/node_modules/@fastify/under-pressure/index.js:143:30)\n    at Plugin.exec (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/lib/plugin.js:125:28)\n    at Boot._loadPlugin (/Users/richard/osp/bumblebee/node_modules/.pnpm/avvio@8.4.0/node_modules/avvio/boot.js:432:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"}
